- SwiftyBeaver.podspec
Managed to get CocoaPod support in without changing the layout of the project which makes things nice and easy :wink: 
In order to push this to CocoaPods once merged there are just a few last steps which you need to do as the owner/maintainer:
* Create Pod trunk account [here](https://guides.cocoapods.org/making/getting-setup-with-trunk)
* `pod trunk push NAME.podspec`
To update in future just update the version number and tag name in the podspec and push to trunk :+1: 
Fixes #9
> Initial commit for CocoaPod support

- sources/SwiftyBeaver.swift
Sry for changing your code with something simple cosmetic. But i try to learn more and more about the Swift statements and looking through your code is helping a bit finding similar things in my own code.
> Usage of Guard Statements

- SwiftyBeaverTests/BaseDestinationTests.swift
- sources/BaseDestination.swift
- sources/ConsoleDestination.swift
- sources/FileDestination.swift
- sources/SwiftyBeaver.swift
> Added printing of thread.

- sources/BaseDestination.swift
- sources/SwiftyBeaver.swift
Hi
I've added asynchronously option in BaseDestination, and a small revise.
How do you think?
https://github.com/SwiftyBeaver/SwiftyBeaver/issues/76
> Add Asynchronously option in BaseDestination

- .travis.yml
- README.md
Fixes #78 
Also fixed broken URL links in README related to Travis build (link didn't work)
> Fix for broken Travis build

- sources/BaseDestination.swift
Previously, the filter logic grouped the filters into categories;
Level, Path, Function and Message. Within each category, all
required filters had to pass and at least one non-required filter
had to pass. Then, each category was ANDed together to make
sure all filters passed according to these rules.
This change slightly alters the logic and the results are nearly identical. However,
it is likely easier to understand. Now, all required filters are gathered regardless of
category and all must pass. Then, all non-required filters are gathered and at least
one of them must pass and then both groups must pass.
> Tweak the filter logic when applying filters

- SwiftyBeaver.xcodeproj/project.pbxproj
- SwiftyBeaver.xcodeproj/xcshareddata/xcschemes/SwiftyBeaver (macOS).xcscheme
- SwiftyBeaverTests/SBPlatformDestinationTests.swift
- sources/AES256CBC.swift
- sources/SBPlatformDestination.swift
- sources/SwiftyBeaver.swift
> Converted to Xcode 8 Beta 3 and new Swift 3 syntax, renamed macOS target

- SwiftyBeaverTests/SBPlatformDestinationTests.swift
- sources/AES256CBC.swift
- sources/BaseDestination.swift
- sources/FileDestination.swift
- sources/SBPlatformDestination.swift
Not sure how you want to handle the Error enums and the changes to Implicitly Unwrapped Optionals for the URLs.
> Fixed Xcode 8 Beta 4 issues and Swift 3 changes.

- sources/BaseDestination.swift
Use open on BaseDestination to allow subclassing
> Swift 3 fixes

- SwiftyBeaverTests/BaseDestinationTests.swift
- sources/BaseDestination.swift
- sources/Filter.swift
Added isExclude() to CompareType to know if a filter is an exclude type.
Added Tests to test exclude filter logic.
> Exclude filters are applied to all messages regardless of minLevel

- SwiftyBeaver.xcodeproj/project.pbxproj
Something got lost since #117 so here we are again :)
> change missing min macOS deployment target version

- sources/FileDestination.swift
I needed a way to clear logs for `FileDestination` so I created `removeFile` function in `FileDestination` to accomplish that.
Let me know what you think.
Thanks for this awesome framework! 👍
> Add removeFile function for FileDestination

- Sources/BaseDestination.swift
Fixes https://github.com/SwiftyBeaver/SwiftyBeaver/issues/185
> Honor the "required" flag for filters.

- CHANGELOG.md
- Sources/SwiftyBeaver.swift
- SwiftyBeaver.podspec
> version bump to 1.2.1

- SwiftyBeaver.xcodeproj/project.pbxproj
Fix  Compile fail in case-sensitive filesystem #218
> Fix case-sensitive bug

- SwiftyBeaver.xcodeproj/project.pbxproj
https://github.com/SwiftyBeaver/SwiftyBeaver/issues/224
The reason is source files is not contained in target macOS(and others except iOS)
> Fix issue 224, build invalid framework for macOS

- Dockerfile
- Sources/BaseDestination.swift
- Sources/ConsoleDestination.swift
- Sources/FileDestination.swift
- Sources/GoogleCloudDestination.swift
- Sources/SBPlatformDestination.swift
- Sources/SwiftyBeaver.swift
- SwiftyBeaver.xcodeproj/project.pbxproj
- SwiftyBeaver.xcodeproj/xcshareddata/xcschemes/SwiftyBeaver (iOS).xcscheme
- Tests/SwiftyBeaverTests/FileDestinationTests.swift
- Tests/SwiftyBeaverTests/GoogleCloudDestinationTests.swift
Sometimes destination needs to pass extra parameters or route the message to a different destination according to these extra parameters.
> Add context parameter to log functions

- Sources/AES256CBC.swift
- Sources/Base64.swift
- Sources/SBPlatformDestination.swift
- SwiftyBeaver.xcodeproj/project.pbxproj
Foundation `String.base64EncodedString`  is broken on Linux.
> fix base64 encoding on Linux

- Dockerfile~swift4
- Sources/AES256CBC.swift
- Sources/BaseDestination.swift
- Sources/SwiftyBeaver.swift
- circle.yml
- test_in_docker.sh
> swift 3 and 4 compatibility 

- SwiftyBeaver.xcodeproj/xcshareddata/xcschemes/SwiftyBeaver (iOS).xcscheme
See https://github.com/Carthage/Carthage/issues/2056.
> iOS: disable code coverage to fix app submission with Xcode 9

- CHANGELOG.md
- Sources/SwiftyBeaver.swift
- SwiftyBeaver.podspec
- Disabled code coverage to fix app submission with Xcode 9
- new version 1.4.1
> Fix Xcode 9 App Submission

- Sources/SBPlatformDestination.swift
Closed an issue discussed here: https://github.com/SwiftyBeaver/SwiftyBeaver/issues/257
> leak on sendToServerAsync() - closed

- SwiftyBeaver.podspec
- SwiftyBeaver.xcodeproj/project.pbxproj
This fixes breaking build on case-sensitive file systems.
> Fix lowercase 'sources' folder name

- Sources/SwiftyBeaver.swift
- SwiftyBeaver.xcodeproj/project.pbxproj
Static declarations are implicitly `final`; use `public` instead of `open`
> fixed Xcode 10 warning

- SwiftyBeaver.xcodeproj/project.pbxproj
Extends #320 to cover all targets
> Swift 5 for all targets

- README.md
Package manager description was outdated.
> Update package manager description in Readme.md

- README.md
> Add Privacy section to README

- Package.swift
Following convention  mentioned at https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md
> Changed properties of a Package to a single nested initializer statement

- Info.plist
- SwiftyBeaver.xcodeproj/project.pbxproj
> restored info.plist

- Package.swift
Aligned minimum supported version of platforms between spm and cocoapods.
> Aligned minimum supported versions

- CHANGELOG.md
- Info.plist
- README.md
- Sources/AES256CBC.swift
- Sources/SwiftyBeaver.swift
- SwiftyBeaver.podspec
More cryptographically secure random text generator; removal of Swift 3 support
> Removal of Swift 3 support

- Sources/AES256CBC.swift
> Fix PKCS7.add: removed unreachable code

- SwiftyBeaver.xcodeproj/project.pbxproj
> Fixes dylib linking issue

- Sources/FileDestination.swift
When using the `FileDestination` from different processes and clearing the log file now and then a race condition can cause a crash because creating a file and writing to it is not atomic. This PR fixes that issue.
> Make appending log in FileDestination atomic operation

- Sources/SBPlatformDestination.swift
- Tests/SwiftyBeaverTests/SBPlatformDestinationTests.swift
> remove process hostname to avoid needing iOS 14 Local Network Permission

- README.md
- Sources/FileDestination.swift
- Tests/LinuxMain.swift
- Tests/SwiftyBeaverTests/SwiftyBeaverTests.swift
by ignoring / not compiling not implemented Linux functionalities of Swift
> fixed failing CI

- Sources/SBPlatformDestination.swift
My app get crashed for many times at "specialized SBPlatformDestination.sendToServerAsync(_:complete:) + 313. +[NSJSONSerialization dataWithJSONObject:options:error:]".
@skreutzberger Please check it.
> Added a safety guard before converting JSON to the Data object.

- Sources/FileDestination.swift
> Revue50 rotating log files

- Sources/SwiftyBeaver.swift
Allow for subclasses to override the logged threadname
> Allow for subclasses to customize the threadname

- Sources/BaseDestination.swift
Gonna need this when OS's calendar is not gregorian.
> Make formatter.calendar customizable

- Sources/SwiftyBeaver.swift
- Tests/SwiftyBeaverTests/DestinationSetTests.swift
**Motivation**
The project I'm working on has a crash that happens on live builds on the AppStore, and that crash happens in SwiftyBeaver. In fact, that crash is currently our top crash.
After looking into the code, it looked like the cause was that the log destination could sometimes be mutated while logging messages. Access to `destinations` is not thread safe right now.
I was able to confirm this theory and reproduce the exact same crash / stack trace by adding a new unit test to the project.
**Solution**
The fix is to ensure all accesses to `destinations` are synchronized. This is achieved by creating a dedicated `DispatchQueue` that is concurrent, but uses the `barrier` flag to make write accesses.
The fix was confirmed to work by running the new unit test again with success.
> Fix race condition when accessing log destination from different threads

- .circleci/config.yml
- .github/workflows/api-breakage.yml
- .github/workflows/tests.yml
Runs unit tests on macOS and different versions of Swift (5.4, 5.5, 5.6, 5.7).
Removes old CircleCi integration.
> Adding Github action

- Sources/FileDestination.swift
This change allows older files to be treated the same way by the operating system as the most recent log file.
For example, `MyAppLogfile.log` becomes `MyAppLogfile.1.log` when rotated, instead of `MyAppLogfile.log.1`
> Preserve the original extension when rotating files

- README.md
Previously, it only referenced app delegate
> Improve README with recommendations for SwiftUI

- Sources/BaseDestination.swift
- Sources/ConsoleDestination.swift
- Sources/GoogleCloudDestination.swift
- Sources/SwiftyBeaver.swift
HI everyone:
Add support for OSLog API.
Add critical and fault log level to match the new OSLog API.
> add support for OSLog API
