SwiftyBeaver/SwiftyBeaver

SwiftyBeaver.podspec

* Add support for watchOS2 extensions
* Created new project with a watchOS app
* Added file to Podfile (example below)
* Tested
* Profit :dollar: :moneybag: 
```ruby
use_frameworks!
target 'Test' do
end
target 'Test WatchKit App' do
end
target 'Test WatchKit Extension' do
platform :watchos, '2.0'
pod 'SwiftyBeaver', :path => '../SwiftyBeaver'
end
```

Add support for watchOS2

---

README.md

Not just SwiftyBeaver.swift, because you'll get errors to the effect of
`Use of undeclared type 'BaseDestination'`

Include all source files if installing manually

---

sources/BaseDestination.swift

Instead of using the variable 'ok', the use of return statements is reducing unnecessary loop iteration time. In this case, the variable ok won't be changed if the first case is true, so you can return there already.

Use of return statements

---

README.md

The Carthage instructions had some extra back ticks that broke the Markdown rendering of the Carthage URL.

Update Carthage instructions in README.md

---

sources/BaseDestination.swift
sources/ConsoleDestination.swift
sources/FileDestination.swift

Allow `BaseDestination` to be overridden by making overridable methods `public`. Swift’s default is `internal` which means that subclasses in a different module cannot override those methods.
This is important because the best way to import Swift dependencies is to link against dynamic frameworks.

Allow BaseDestination to be overridden

---

SwiftyBeaver.podspec
sources/SwiftyBeaver.swift

I have a command line program I am using Swifty Beaver in, my problem was the main thread ends and the last log entry or two never gets written. That was because those messages were on the background queue and hadn't been processed yet. So I added a simple flush method with timeout to the top level object. It uses a dispatch group to keep track of how many destinations are sent a flush message, the flush message reducing the dispatch group. then a wait, which will block until the flush messages are processed or the timeout is reached.
testing in my prenagha/alamofire-example project and seems to work well
thought others might find it useful

add flush option

---

SwiftyBeaverTests/SwiftyBeaverTests.swift
sources/SwiftyBeaver.swift

This changes the log functions to have signatures like:
```
public class func error(@autoclosure message: () -> CustomStringConvertible, _ path: String = __FILE__, _ function: String = __FUNCTION__, line: Int = __LINE__)
```
This change would break any code where someone was passing in an object that does not conform to `CustomStringConvertible`.

Changes log functions to take an @autoclosure

---

sources/BaseDestination.swift
sources/SwiftyBeaver.swift

Thought those of you working on log destination to remote systems (Loggly #67 ...) would find this useful. Creates a flush method on the destination that gets called as part of the main flush process. So if you are buffering in the destination this hook gives you a place to flush/send those log items to the remote server before the system shuts down.

Flush hook for each destination

---

SwiftyBeaverTests/SwiftyBeaverTests.swift
sources/BaseDestination.swift
sources/FileDestination.swift

With a white XCode background some colors like yellow are unreadable. With this change the user can modify log colors.

Log colors made public and editable

---

sources/SwiftyBeaver.swift

These were deliberately being thrown away, but for no apparent reason.
The log message will eventually contain useful information, like the
source location, time, and thread, and so there's value in having a log
message emitted even if the "message" is empty.
This means that client code can do log.debug("") and still see when that
line is reached, or log.error("\(serverError)") and still see that
something bad happened, even if the server returned nothing.

Allow empty log messages.

---

sources/BaseDestination.swift

Just a small update to the default log level colors, so they match the colors of the log level filter labels in the mac app... (much more aesthetically pleasing)

Update Console Log Level Default Colors

---

SwiftyBeaverTests/SwiftyBeaverTests.swift
sources/BaseDestination.swift

added a `coloredLines` flag
defaults to `false`
set to true and the entire log line is output with the level color

Add option to have entire log line colored

---

SwiftyBeaver.xcodeproj/project.pbxproj
SwiftyBeaverTests/DestinationSetTests.swift
sources/SwiftyBeaver.swift

Make the `destinations` property `public private(set)`. This allows consumers of `SwiftyBeaver` to iterate through the `destinations` to make changes, rather than having to store their own collection of destinations.

Expose destinations property (read-only)

---

sources/SwiftyBeaver.swift

Though most of the time, message resolution will likely not be expensive, this
change moves the resolution of the message to the asynchronous dispatch queue.
In order to accommodate this change, I had to change all @autoclosure annotations to
@autoclosure(escaping). According to the article posted here:
http://ericasadun.com/2015/04/30/swift-a-little-autoclosure-hacking/, non escaping @autoclosures
provide minor performance optimizations.

Move message resolution to background

---

SwiftyBeaverTests/AES256CBCTests.swift
SwiftyBeaverTests/BaseDestinationTests.swift
SwiftyBeaverTests/SBPlatformDestinationTests.swift
sources/AES256CBC.swift
sources/BaseDestination.swift
sources/ConsoleDestination.swift
sources/FileDestination.swift
sources/SBPlatformDestination.swift
sources/SwiftyBeaver.swift

This version builds and passes tests on both Swift 3 DEVELOPMENT-SNAPSHOT-2016-05-09 and Swift 2.2.
Please be aware of the potential maintenance implications.
In Swift 3, by the first parameter is no longer removed by default and, unfortunately, you can’t #if #endif out just the function declaration, you have to do the entire function. From SE-0020, "Like other build configurations, #if swift isn't line-based - it encloses whole statements or declarations."
Given this, I erred on the side of maintaining your current public APIs, however since the philosophy of the first parameter has changed in Swift 3, you’ll probably want to look into updating the API.
As an example,
`class func encryptString(_ str: String, password: String) -> String? {`
would probably become
`class func …

Add Swift 3 swift-DEVELOPMENT-SNAPSHOT-2016-05-09 compatibility.

---

SwiftyBeaverTests/BaseDestinationTests.swift
sources/BaseDestination.swift
sources/SwiftyBeaver.swift

It might be desirable to further filter messages based upon the message content itself.
Since filtering by message content first requires that the message be resolved to a String, thereby
defeating the purpose of the @autoclosure, the minLevelFilters are first applied. If the message is
not filtered by the level filtering using level, path and function, then the message is resolved
(once instead of once for each destination) and if there are any message filters in place, those
are invoked to see if any message filters reject the message.
This change provides additional flexibility for content-based filtering where level, path and function filtering
is not enough.
Resolving the message once for each destination introduces the remote possibility of a bug. If the expression
changes each time …

Add optional message filter to BaseDestination

---

sources/BaseDestination.swift

Don't know why but changing `\(line)` to `\(String(line))` fixes a leak.

Fix memory leak in formattedMessage on string interpolation

---

ContentFilter.swift
SwiftyBeaver.xcodeproj/project.pbxproj
SwiftyBeaverTests/BaseDestinationTests.swift
SwiftyBeaverTests/BasicContentFilterTests.swift
sources/BaseDestination.swift
sources/SwiftyBeaver.swift

This PR allows Content Filters to be added to a destination to further
control what gets sent to the destination. A ContentFilter, when applied, answers
true or false. Answering true allows the message to be logged. If multiple content
filters have been added to a destination, ANY filter answering true will allow the message
to be logged even if others answer false.

Add content filtering

---

sources/ConsoleDestination.swift

First argument to `NSLog` is a format specifier. We shouldn't pass a user specified string directly to the format specifier argument (security issue, can crash).

Use a format specifier for NSLog statement

---

SwiftyBeaver.xcodeproj/project.pbxproj

These appear when the Framework is embedded in your Application.

Enabled Application Extension API Only to remove Xcode Warnings

---

SwiftyBeaver.xcodeproj/project.pbxproj

Previously, the value was empty and building with Carthage resulted in the most recent 10.11 SDK to be required.

set OS X target to 10.10

---

sources/SBPlatformDestination.swift

The "Documents" folder does not exist on Apple TV hardware and so at the moment the framework fails to initialise.   
An Apple TV app can only store data in the UserDefaults, Cloud or Cache folder - see
https://developer.apple.com/library/prerelease/content/documentation/General/Conceptual/AppleTV_PG/
As such the framework needs to initialise using the Cache folder during startup rather then the Documents - just for tvOS..

Support running on Apple TV hardware

---

sources/AES256CBC.swift

As you know, encryption did not pass unit tests on XCode 8 Beta 6. This pull request fixes that by reimplementing `randomText` and restoring the commented out `arrayOfBytes` with minor tweaks to make it work again.

Fix encryption to pass unit tests on XCode 8 Beta 6

---

SwiftyBeaver.xcodeproj/project.pbxproj

Carthage was failing with Xcode 8 for tvOS/watchOS/macOS (it was working ok with iOS). I have updated each target to Swift 2.3 and all platforms now build successfully. 
There were no source changes, building with Xcode 7 continues to work fine.

Migrate tvOS/watchOS/macOS targets to Swift 2.3 (no source changes)

---

SwiftyBeaverTests/BaseDestinationTests.swift
SwiftyBeaverTests/FilterTests.swift
sources/Filter.swift

The idea is sometimes the filter is just to remove a set of log statements not create filters with just inclusive sets.
The PR includes updates to the tests.

Adding exclude to comparison filters

---

SwiftyBeaver.xcodeproj/project.pbxproj

Previously there was to deployment target set so Xcode
assumed the latest installed deployment target automatically
which lead to #171. This attempts to fix #171.

Explicitly set tvOS deployment target

---

SwiftyBeaver.xcodeproj/project.pbxproj

Thanks for an awesome library!!
I started migrating my app to SwiftyBeaver and everything worked great, but my beta users started giving me sad faces because the target watchOS version was too high (it's only supporting the very latest watchOS version).
So I lowered the watchOS version to 3.0 and everything still works and unit tests pass. Would you consider widening the watchOS support like all the other platforms?

Added support for more watchOS versions

---

Sources/BaseDestination.swift
Tests/SwiftyBeaverTests/BaseDestinationTests.swift

As in #185, required filter still doesn't work properly.
```
if allRequired > 0 {
if matchedRequired == allRequired {
return true
}
} else {
// ....
}
if level.rawValue < minLevel.rawValue {
// other code that can eventually return true
}
```
https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/BaseDestination.swift#L362-L378
If I have a required filter that is not matched, the `matchedRequired == allRequired` will not be equal, and then the code flow would just skip to the check about the destination min level. Instead, it should be `return matchedRequired == allRequired` to see if the validation succeeds or not. If those values are not equal, means that at least one required validator didn't pass, so the log should be discarded.

Fix validation of required filters

---

Sources/SwiftyBeaver.swift
Tests/SwiftyBeaverTests/SwiftyBeaverTests.swift

Here is another bug fix PR ;)
Basically if you have two or more destinations with a message filter attached, the message itself is analyzed just by the destinations with odd indexes (1st, 3rd...).
```
var resolvedMessage: String?
for dest in destinations {
// ...
resolvedMessage = resolvedMessage == nil && dest.hasMessageFilters() ? "\(message())" : nil
if dest.shouldLevelBeLogged(level, path: file, function: function, message: resolvedMessage) {
```
[Here](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SwiftyBeaver.swift#L126-L134)
On the first destination, `resolvedMessage` will be nil, and `dest.hasMessageFilters()` will return true, so `resolvedMessage` will contain the disclosed message from the autoclosure.
Then the problem: on second destination, `resolvedMessage` …

Fixes issue with multiple destinations with message filters

---

Sources/FileDestination.swift

Without this, I have seen apps crash when logs are being written to a file with the phone locked.

Set file protection to FileProtectionType.none when log file is created

---

SwiftyBeaver.xcodeproj/project.pbxproj

These add unnecessary size to the frameworks, they shouldn't be included in the targets.

Removed LICENSE and Podspec from frameworks

---

Sources/AES256CBC.swift
Sources/BaseDestination.swift
Sources/Extensions.swift
Sources/SBPlatformDestination.swift
Sources/SwiftyBeaver.swift
SwiftyBeaver.xcodeproj/project.pbxproj
Tests/SwiftyBeaverTests/AES256CBCTests.swift
Tests/SwiftyBeaverTests/GoogleCloudDestinationTests.swift
Tests/SwiftyBeaverTests/SBPlatformDestinationTests.swift
Tests/SwiftyBeaverTests/SwiftyBeaverTests.swift

In version 1.4.3 we silenced deprecation warnings for Swift 3.2 and Swift 4 which unfortunately also removed support for Swift 3.1.
This PR here is bringing back support for Swift 3.1 but still silences the deprecation warnings under Swift 3.2+

String counting works under Swift 3.1 & Swift 3.2+

---

Sources/BaseDestination.swift

Changes non-required filter behavior so that, when non-required filters exist, at least one non-required filter must match. Previously in this case it would exit the conditional block and be able to pass (return true) if the log level check passed.
This adds more flexibility to the log filtering; specifically it allows the scenario where you want to send logs to a destination ONLY if it matches *either* Case A or Case B.
Previously this setup,
```
someDestination.addFilter(Filters.Function.equals("methodA", required: false))
someDestination.addFilter(Filters.Function.equals("methodB", required: false))
```
resulted in all log messages being sent to someDestination, which isn't any different than not specifying filters. With this PR `someDestination` only received messages from `methodA` …

If they exist, require at least one passing non-required filter

---

Sources/BaseDestination.swift
Tests/SwiftyBeaverTests/BaseDestinationTests.swift

Fixes issues/requests #294 and #295.
Bugs fixed:
* Context format specification with $X ate the remainingText if context was nil.
* First character in the format was potentially always treated as a format character, even without a $ prefix, so `"Level: $L"` would yield `"DEBUGevel: DEBUG"`.
New feature:
* Format supports padding for prettier output in console (with monospaced font)
Including unit tests for new functionality.
Documentation about the new format feature is not included (since those files are not part of this repo).
The new feature is to pad formatted output so that it has better readability in the console output with clean columns. Format is an extention of the existing
`$<formatChar>`
to 
`$<paddedLength><formatChar>`
Negative values give right padding, positive left …

Padded format

---

Sources/BaseDestination.swift

The `SwiftyBeaver` singleton uses the internal `BaseDestination.queue` to deliver messages with the overridden `send()`. If the destination needs to synchronize access to the current storage for other non-logging means (e.g. uploading a snapshot somewhere), there's no way to sync with the internal queue, because it's inaccessible to subclasses. If `send()` writes to a shared resource, mutex must be done on an additional queue.
Of course a refactoring is not viable, and exposing the queue may be too much. Providing a couple `execute()` methods to only expose what's necessary, both in sync and async fashion.
OT: could `queue` be made non-optional? I see it's optional to use target = self, but maybe it's some dragged legacy.

Provide execute() methods to run in destination queue

---

Sources/FileDestination.swift
SwiftyBeaver.podspec

My goal was to enable reading from the log file *immediately* after a write and to read the contents just written. This seems a step in the right direction but doesn't actually fully do the job. Any suggestions would be great. See also https://stackoverflow.com/questions/50311546/ios-flush-all-output-files/50311616

Added optional sync after each file write.

---

Sources/BaseDestination.swift
Sources/SBPlatformDestination.swift

Looks like SourceKit doesn't support renaming nested classes used inside switch block, so I'd suggest using swift type inference for it.

Use swift type inference to allow SwiftShield to obfuscate code

---

SwiftyBeaver.xcodeproj/project.pbxproj

Building with Carthage and using the Xcode 10.2 compile chain, it appears support for Swift 3.0 is dropped.  
```
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SwiftyBeaver (iOS)')
Build system information
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SwiftyBeaver (iOS)')
Build system information
warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "SwiftyBeaver (iOS)" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'SwiftyBeaver (iOS)')
Build system information
warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "SwiftyBeaver (iOS)" to Swift 4.2 using …
```

Building with Xcode 10.2 and Carthage

---

Sources/BaseDestination.swift
Sources/Filter.swift
Sources/FilterValidator.swift
SwiftyBeaver.xcodeproj/project.pbxproj
Tests/SwiftyBeaverTests/BaseDestinationTests.swift

This issue was discussed in #339. When a destination has non-required filters set, it doesn't output any messages that are not matching at least one of these filters.
I've refactored the filtering logic from `BaseDestination` into a separate struct `FilterValidator`. Please feel free to rename, edit or move this file to another location. I've also added two new unit tests and documentation comments.

Fixed logging issue in BaseDestination with non-required filters

---

Sources/FileDestination.swift
Tests/SwiftyBeaverTests/FileDestinationTests.swift

Hi.
I caught a problem in one of my projects. It has a Launch Daemon that writes logs. Over time, the logs become a lot and the user decides to clean them. But the user deletes not the files, but the whole folder with the logs. At this time, the daemon is still running, but can not write logs. I cannot handle this situation either. Only if the daemon is restarted.
Therefore, I decided to create a folder if it does not exist.

Create folder if not exist for file destination log

---

Info.plist
Sources/SwiftyBeaver.swift
SwiftyBeaver.podspec
SwiftyBeaver.xcodeproj/project.pbxproj

Apps using Carthage were unable to be uploaded to the App Store due to a missing CFBundleVersion. The CFBundleVersion was (and still is) set to $(CURRENT_PROJECT_VERSION) but the CURRENT_PROJECT_VERSION was set to itself, making it blank.

Fix missing CFBundleVersion

---

Sources/SBPlatformDestination.swift

This is required to fix builds on Linux (like in Docker),
as types like URLSession have been moved from the `Foundation`
module to the new `FoundationNetworking` module, which seems to
have diverged from Darwin and been accepted without a formal proposal
review.
Pitch: https://forums.swift.org/t/pitch-move-urlsession-to-new-foundationnetworking-module/14002
Pull Request: https://github.com/apple/swift-corelibs-foundation/pull/2289
---
This shows the problem with the code on `master` that this fixes, inside the current `swift:5.1` Docker image.

Fix broken build on Linux/Docker Swift 5.1

---

SwiftyBeaver.xcodeproj/project.pbxproj

The checkbox was disabled during the project file recovery in #354. This causes Xcode warnings when app extensions link against the SwiftyBeaver framework.
> Linking against a dylib which is not safe for use in application extensions: <Project Directory>/Carthage/Build/iOS/SwiftyBeaver.framework/SwiftyBeaver

Enabled 'Allow app extension API only' checkbox in project settings

---

SwiftyBeaver.podspec

Hello.
Thank you for SwiftyBeaver.
In this pull request I added supported Swift versions to SwiftyBeaver.podspec. Currently getting the following error: **- `SwiftyBeaver-iOS` does not specify a Swift version and none of the targets integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod**.

Add supported Swift versions to SwiftyBeaver.podspec

---

Sources/FileDestination.swift

When using FileDestination the log lines contain the escape characters for visualizing log levels by using colors. For those who don't want colors at all this PR adds the ability to enable and disable colors.
This feature has been requested in the past in #309 but hasn't been implemented yet.

Add ability to enable colors in FileDestination

---

Sources/SwiftyBeaver.swift
Tests/SwiftyBeaverTests/SwiftyBeaverTests.swift

Threads are currently being named by the address and not by a more human readable name. This pull request fixes that behaviour by modifying the threadName function name the thread based on the output of __dispatch_queue_get_label. Added unit test to verify behaviour remains unchanged for the main thread and that the correct name is used for a standard global DispatchQueue and for a DispatchQueue with a custom name

Provide more human readable thread name information #376

---

Sources/FileDestination.swift

This adds thread-safety to log file access.
This is particularly useful when dealing with multiple processes, e. g. when developing an iOS app that has an app extension. Due to the sandbox mechanism the default log file is distinct from the other processes' log file. By passing a custom log file url they all can log to the same file. Accessing the log file via NSFileCoordinator ensures thread-safety even across multiple processes.

Use NSFileCoordinator for thread-safe log file access

---

Package.swift

This PR removes explicit deployment targets for SwiftyBeaver when using Swift Package Manager.
In Xcode 12.0 beta bumped the minimum supported deployment target to iOS 9.0. SwiftyBeaver explicitly declared iOS 8 as a minimum deployment target results in a warning/error when building SwiftUI previews.
Xcode 11 users will be unaffected as the explicitly chosen OS deployment targets are the default minimum deployment targets.

Removes default platform deployment targets from Package.swift file

---

README.md

@skreutzberger Clicking the link does not work, needed to remove a `/`

Fix log format link

---

Sources/BaseDestination.swift
Sources/Filter.swift

This is a workaround for this issue.
- iOS 14 support #409
The problem seems to be caused by a bug in Xcode12 beta related to String type inference.
Undefined symbol: type metadata for Swift._StringObject.Variant
https://developer.apple.com/forums/thread/649918
This problem is also reproduced in beta 1 and beta 2.
This fix in this pull request may seem useless as it does not affect the behavior of this SDK.
But it will help developers who use Xcode 12 beta.

Workaround for Xcode12 build error

---

Sources/FileDestination.swift

I would like to pre-process the message that goes to a certain file location. For that, I would like to subclass the `FileDestination` and overwrite `send` to process the message before passing it to the super class.

Allow subclassing of FileDestination

---

Sources/FileDestination.swift

The original code would skip the `.1` file since `stride(from: to: by:)` excludes the final index, `firstIndex`. 
If this file exists the last move operation would error out with 
```
rotateFile error: Error Domain=NSCocoaErrorDomain Code=516 "“logfile.log” couldn’t be moved to “logs” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/var/mobile/Containers/Data/Application/975837DF-7FDA-41A9-8EEB-33A2948D35AB/Library/Application Support/logs/logfile.log, NSUserStringVariant=(
Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/975837DF-7FDA-41A9-8EEB-33A2948D35AB/Library/Application Support/logs/logfile.log.1, NSFilePath=/var/mobile/Containers/Data/Application/975837DF-7FDA-41A9-8EEB-33A2948D35AB/Library/Application …
```

Fix File Rotation

---

Sources/ConsoleDestination.swift
Sources/FileDestination.swift
Sources/SBPlatformDestination.swift

This PR sets the access levels of `ConsoleDestination`, `FileDestination`, and `SBPlatformDestination` to `open`, which allows for subclassing. I needed to modify the behavior of these destinations, for example, to add device-specific information when creating new log file entries. The most straightforward way to achieve this was to create a custom subclass and override the `send` method. But I'm also happy to discuss alternative approaches.

Allow subclassing of destinations

---

Sources/FileDestination.swift

It will crash,  if no free space is left on the file system, or if any other writing error occurs. 
Here is the crash I met：
```
CrashDoctor Diagnosis: Application threw exception NSFileHandleOperationException: *** -[NSConcreteFileHandle writeData:]: No space left on device
Originated at or in a subcall of AudioFile<double>::getAiffSampleRate(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, int)
Thread 16 Crashed:
0   CoreFoundation                      0x00000001aa421344 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001aa136cc0 objc_exception_throw
2   Foundation                          0x00000001aa7c4050 -[NSConcreteFileHandle readDataUpToLength:error:]
3   Foundation                          0x00000001aa74f504 -[NSConcreteFileHandle …
```

Fix write data crash

---

Sources/SwiftyBeaver.swift

I am unsure why those were anonymous parameters, but I feel like they shouldn't be, because it's very easy to produce unexpected results.
I certainly got surprised by this, until I looked at the source code.
----
I assume most people were using `print` statements prior to using a logger, where you would have:
```swift
print("Some error happened: ", error.localizedDescription)
print("Foo", "Bar", "FooBar")
```
If you replace the `print` statements with `log.debug`, the code will compile correctly.
```swift
log.debug("Some error happened: ", error.localizedDescription)
log.debug("Foo", "Bar", "FooBar")
```
But the 2nd and 3rd arguments will be passed as `file` and `function`, instead of the default values `#file` and `#function`
At least now, if you write code above, you will get a compiler …

Remove anonymous parameters on file and function

---

README.md

Heya, just going through the documentation and noticed there was two `log.addDestination(console)` in the documentation following https://github.com/SwiftyBeaver/SwiftyBeaver/pull/495. Thought it should be removed. Thanks!

Remove second  `log.addDestination(console)` in documentation

---

PrivacyInfo.xcprivacy

When the APP is reviewed, you will receive the following warning:
> ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path:
> "xxx/PrivacyInfo.xcprivacy". NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn't empty. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app's privacy manifest must be valid. For more details about privacy manifest files, visit:
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

Turn off privacy tracking

---

Sources/ConsoleDestination.swift

HI All:
I modified the default printing method of ConsoleDestination to print to ensure that users can still see log outputs when OS_ACTIVITY_MODE=disable is set.

fix: Modify the default printing method of ConsoleDestination to print.

---

README.md

HI Every one:
I have updated the README to illustrate how to enable OSLog printing with color, subsystem, and category information in Xcode 15.
However, I haven't found a way to display colors when viewing files in the terminal. So I haven't replaced the second image.

Update README.md to demonstrate enabling OSLog printing in Xcode 15.

---

Sources/SwiftyBeaver.swift

Adding `Sendable` support to `SwiftyBeaver.Level`, so that we can use it in Swift 6 concurrency context.

Add Sendable support to SwiftyBeaver.Level

---

Sources/ConsoleDestination.swift
Tests/SwiftyBeaverTests/ConsoleDestinationTests.swift

Replace hearts with squares.
I've matched the console destination so that the verbose is no longer purple but silver, as in the text-only mode.

Update ConsoleDestination.swift: Replace hearts with squares fix #536
